name: Twitter Bot Automation

on:
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours
    - cron: '*/10 * * * *' # Runs every 10 minutes
    - cron: '0 */4 * * *' # Runs every 4 hours
    - cron: '0 9 * * *' # Runs daily at 9 AM
    - cron: '0 */6 * * *' # Runs every 6 hours

  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  run-cron-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST request to Next.js API
        run: |
          curl -X POST https://cdptoolkit.vercel.app/api/cron -d '{"job": "tweetEvery3Hours"}' -H "Content-Type: application/json"
          curl -X POST https://cdptoolkit.vercel.app/api/cron -d '{"job": "replyToMentionsEvery10Minutes"}' -H "Content-Type: application/json"
          curl -X POST https://cdptoolkit.vercel.app/api/cron -d '{"job": "monitorTrendsEvery4Hours"}' -H "Content-Type: application/json"
          curl -X POST https://cdptoolkit.vercel.app/api/cron -d '{"job": "dailyFollowerAnalysis"}' -H "Content-Type: application/json"
          curl -X POST https://cdptoolkit.vercel.app/api/cron -d '{"job": "postPollAt9AM"}' -H "Content-Type: application/json"
          curl -X POST https://cdptoolkit.vercel.app/api/cron -d '{"job": "searchTweetsUsingTrendsEvery6Hours"}' -H "Content-Type: application/json"
